//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADDRESS
    {
        public int ID { get; set; }
        [Display(Name="Personel Adý")]
        [Required(ErrorMessage ="personel seçimi yapýlmalý...")]
        public Nullable<int> PERSONELID { get; set; }
        [Display(Name = "Ülke")]
        [Required(ErrorMessage = "Ülke Girilmeli...")]
        public string COUNTRY { get; set; }

        [Display(Name = "Þehir")]
        [Required(ErrorMessage = "Þehir Girilmeli...")]
        public string CITY { get; set; }

        [Display(Name = "Ýlçe")]
        [Required(ErrorMessage = "Ýlçe Girilmeli...")]
        public string TOWN { get; set; }
        [Display(Name = "Semt")]
        [Required(ErrorMessage = "Semt Girilmeli...")]
        public string DISTRICT { get; set; }
        [Display(Name = "Açýk Adres")]
        [Required(ErrorMessage = "Açýk Adres Girilmeli...")]
        public string ADDRESSTEXT { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
